namespace StockTrackerApp.Constants;

public class StockSymbols {
    public static List<string> Symbols = new List<string>
    {
        // "WBA",
        // "PRU",
        // "BLK",
        // "UNP",
        // "MA",
        // "WHA",
        // "AGN",
        // "LLY",
        // "TKG",
        // "INTC",
        // "BATS",
        // "ALX",
        // "BK",
        // "AGS",
        // "T",
        // "ACB",
        // "SLB",
        // "DHR",
        // "TMO",
        // "ENX",
        // "BOLS",
        // "REL",
        // "COP",
        // "ASM",
        // "PFE",
        // "HD",
        // "URW",
        // "PHARM",
        // "WDP",
        // "ABI",
        // "VALUE",
        // "PBH",
        // "NOKIA",
        // "AD.AS",
        // "QCOM",
        // "BAS",
        // "EMR",
        // "ACOMO",
        // "KER",
        // "JNJ",
        // "BMW",
        // "TOM2",
        // "AKZA",
        // "VZ",
        // "ACN",
        // "ORDI",
        // "MT",
        // "KHC",
        // "SAF",
        // "NEE",
        // "BCS",
        // "GM",
        // "CSCO",
        // "EBUS",
        // "FDX",
        // "BESI",
        // "SIE",
        // "ABNB",
        // "NVS",
        // "AMT",
        // "ZURN",
        // "IBM",
        // "DIS",
        // "DG",
        // "TTE",
        // "LMT",
        // "OCI",
        // "PG",
        // "TSLA",
        // "BFIT",
        // "CVX",
        // "AMGN",
        // "NVDA",
        // "V",
        // "HEIO",
        // "TKWY",
        // "KO",
        // "HDG",
        // "PYPL",
        // "CMCOM",
        // "VPK",
        // "DD",
        // "SGO",
        // "HOLCO",
        // "NN",
        // "SO",
        // "AVTX",
        // "MDT",
        // "KENDR",
        // "BKNG",
        // "CMCSA",
        // "CBK",
        // "MCD",
        // "BAYN",
        // "CS",
        // "CTPNV",
        // "ESP",
        // "ENGI",
        // "AXS",
        // "SAN",
        // "AALB",
        // "BRK.B",
        // "NG",
        // "BSGR",
        // "GLPG",
        // "IBE",
        // "SLIGR",
        // "UMG",
        // "DGB",
        // "RKT",
        // "ALV",
        // "GE",
        // "ADYEN",
        // "UBSG",
        // "LIGHT",
        // "ABB",
        // "HAL",
        // "BN",
        // "IEX",
        // "ABBV",
        // "EOAN",
        // "IMCD",
        // "BBED",
        // "F",
        // "WFC",
        // "MO",
        // "AZN",
        // "LOW",
        // "BA",
        // "UPS",
        // "DGE",
        // "MRK",
        // "DUK",
        // "PNL",
        // "AI",
        // "LI",
        // "PHIA",
        // "BP",
        // "CAT",
        // "NEDSE",
        // "CVS",
        // "BOKA",
        // "NOV:B",
        // "BAMNB",

        "FUR",
        "OXY",
        "HYDRA",
        "MMM",
        "AF",
        "FFARM",
        "ULVR",
        "GILD",
        "CAP",
        "NFLX",
        "MSFT",
        "ORCL",
        "SBMO",
        "LVIDE",
        "AJAX",
        "PEP",
        "EAS2P",
        "ABT",
        "GOJXN",
        "BRNL",
        "CLB",
        "COF",
        "DTE",
        "TXN",
        "BBVA",
        "MC",
        "INTER",
        "AMUND",
        "SNOW",
        "VOD",
        "COST",
        "RIO",
        "ROOD",
        "IMB",
        "TEF",
        "SBUX",
        "ALFEN",
        "BAC",
        "JDEP",
        "ADBE",
        "FAST",
        "CL",
        "WKL",
        "TIE",
        "FLOW",
        "SPG",
        "ARCAD",
        "AAPL",
        "USB",
        "RAND",
        "SAP",
        "NXFIL",
        "AMG",
        "ASRNL",
        "BRILL.AS",
        "ECMPA",
        "DSM",
        "META",
        "FAGR",
        "RTX",
        "Genmab",
        "KPN",
        "AMZN",
        "BNP",
        "VASTN",
        "UNH",
        "GOOGL",
        "CTAC",
        "ABN",
        "XOM",
        "WMT",
        "ALL",
        "DMLRY",
        "ASML",
        "ENVI",
        "MDLZ",
        "CRBN",
        "NESN",
        "MS",
        "C",
        "PRX",
        "MET",
        "BEVER.AS",
        "CRM",
        "APAM",
        "SU",
        "SHEL",
        "BMY",
        "JPM",
        "HEIJM.AS",
        "OR",
        "AIG",
        "NSI",
        "AXP",
        "NKE",
        "DJI",
        "HON",
        "LIN.DE",
        "TGT",
        "GS",
        "CHTR",
        "HEIA",
        "EXC",
        "KMI",
        "SIFG",
        "NSE",
        "VVY",
        "BIIB"
    };
}
